import React, { useState, useEffect } from 'react';
import { Container, Grid, Paper, Text, Button, Group, Alert } from '@mantine/core';
import { IconServer, IconDatabase, IconBrain } from '@tabler/icons-react';
import { supabase } from '../supabaseClient';
import axios from 'axios';

export function Dashboard() {
                                                                                                    const [backendStatus, setBackendStatus] = useState('checking...');
                                                                                                    const [supabaseStatus, setSupabaseStatus] = useState('checking...');
                                                                                                    const [modelList, setModelList] = useState([]);
                                                                                                    const [error, setError] = useState(null);

                                                                                                    // Check backend health
                                                                                                    const checkBackend = async () => {
                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                            const response = await axios.get(`${import.meta.env.VITE_BACKEND_URL}/api/status`);
                                                                                                                                                                                                                                                                                                            setBackendStatus(response.data.status);
                                                                                                                                                                                                                                                                                                            setError(null);
                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                            setBackendStatus('error');
                                                                                                                                                                                                                                                                                                            setError(err.message);
                                                                                                                                                                                                        }
                                                                                                    };

                                                                                                    // Check Supabase connection
                                                                                                    const checkSupabase = async () => {
                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                            const { data, error } = await supabase.from('health_check').select('*');
                                                                                                                                                                                                                                                                                                            if (error) throw error;
                                                                                                                                                                                                                                                                                                            setSupabaseStatus('connected');
                                                                                                                                                                                                                                                                                                            setError(null);
                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                            setSupabaseStatus('error');
                                                                                                                                                                                                                                                                                                            setError(err.message);
                                                                                                                                                                                                        }
                                                                                                    };

                                                                                                    // List available models
                                                                                                    const listModels = async () => {
                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                            const response = await axios.get(`${import.meta.env.VITE_BACKEND_URL}/api/models`);
                                                                                                                                                                                                                                                                                                            setModelList(response.data.models || []);
                                                                                                                                                                                                                                                                                                            setError(null);
                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                            setError(err.message);
                                                                                                                                                                                                        }
                                                                                                    };

                                                                                                    useEffect(() => {
                                                                                                                                                                                                        checkBackend();
                                                                                                                                                                                                        checkSupabase();
                                                                                                                                                                                                        listModels();
                                                                                                    }, []);

                                                                                                    return (
                                                                                                                                                                                                        <Container size="lg" py="xl">
                                                                                                                                                                                                                                                                                                            <Text size="xl" weight={700} mb="lg">System Dashboard</Text>

                                                                                                                                                                                                                                                                                                            {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                <Alert color="red" mb="lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {error}
                                                                                                                                                                                                                                                                                                                                                                                                                </Alert>
                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                            <Grid>
                                                                                                                                                                                                                                                                                                                                                                                                                {/* Backend Status */}
                                                                                                                                                                                                                                                                                                                                                                                                                <Grid.Col span={4}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Paper shadow="xs" p="md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Group>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <IconServer size={24} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text weight={500}>Backend Status</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Group>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Text mt="sm" color={backendStatus === 'ok' ? 'green' : 'red'}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {backendStatus}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button size="xs" mt="md" onClick={checkBackend}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Check Backend
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Paper>
                                                                                                                                                                                                                                                                                                                                                                                                                </Grid.Col>

                                                                                                                                                                                                                                                                                                                                                                                                                {/* Supabase Status */}
                                                                                                                                                                                                                                                                                                                                                                                                                <Grid.Col span={4}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Paper shadow="xs" p="md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Group>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <IconDatabase size={24} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text weight={500}>Supabase Status</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Group>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Text mt="sm" color={supabaseStatus === 'connected' ? 'green' : 'red'}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {supabaseStatus}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button size="xs" mt="md" onClick={checkSupabase}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Check Supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Paper>
                                                                                                                                                                                                                                                                                                                                                                                                                </Grid.Col>

                                                                                                                                                                                                                                                                                                                                                                                                                {/* Model List */}
                                                                                                                                                                                                                                                                                                                                                                                                                <Grid.Col span={4}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Paper shadow="xs" p="md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Group>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <IconBrain size={24} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text weight={500}>Available Models</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Group>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Text mt="sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {modelList.length > 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                modelList.map((model, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={idx}>{model}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'No models found'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button size="xs" mt="md" onClick={listModels}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Refresh Models
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Paper>
                                                                                                                                                                                                                                                                                                                                                                                                                </Grid.Col>
                                                                                                                                                                                                                                                                                                            </Grid>
                                                                                                                                                                                                        </Container>
                                                                                                    );
}